import { render, screen, waitFor } from '@/tests/intl'
import userEvent from '@testing-library/user-event'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { beforeEach, describe, expect, it, vi } from 'vitest'

const {
  mockRegisterSession,
  mockCompleteSession,
  mockGetSessions,
  mockPush,
  mockWriteMemoryReviewDraft,
} = vi.hoisted(() => ({
  mockRegisterSession: vi.fn(),
  mockCompleteSession: vi.fn(),
  mockGetSessions: vi.fn(),
  mockPush: vi.fn(),
  mockWriteMemoryReviewDraft: vi.fn(),
}))

vi.mock('@/lib/sessions/api', () => ({
  registerSession: mockRegisterSession,
  completeSession: mockCompleteSession,
  getSessions: mockGetSessions,
  SessionApiError: class SessionApiError extends Error {},
}))

vi.mock('@/lib/sessions/memory-review-draft', () => ({
  writeMemoryReviewDraft: mockWriteMemoryReviewDraft,
}))

vi.mock('@/i18n/navigation', () => ({
  useRouter: () => ({ push: mockPush }),
}))

import { LogSessionForm } from '@/components/sessions/log-session-form'
import type { SessionResponse } from '@/lib/sessions/schemas'

const RESPONSE = {
  session_id: 'session-1',
  session_number: 8,
  memory_suggestions: [],
}

/** Render the log-session form inside a fresh QueryClientProvider. */
function renderForm(
  props: Partial<React.ComponentProps<typeof LogSessionForm>> = {}
) {
  const queryClient = new QueryClient({
    defaultOptions: { queries: { retry: false } },
  })
  return render(
    <QueryClientProvider client={queryClient}>
      <LogSessionForm campaignId="camp-1" {...props} />
    </QueryClientProvider>
  )
}

/** Build a session-history row; defaults to a plain logged session. */
function session(overrides: Partial<SessionResponse> = {}): SessionResponse {
  return {
    id: 'session-a',
    session_number: 1,
    summary: 'A logged session.',
    consequences: 'The keep fell.',
    has_generated_content: false,
    status: 'registered',
    created_at: '2026-01-01T00:00:00Z',
    ...overrides,
  }
}

/** An open draft: generated by the Scribe, outcome not yet recorded. */
const OPEN_DRAFT = session({
  id: 'draft-3',
  session_number: 3,
  summary: 'The Scribe proposed a raid on the docks.',
  consequences: null,
  has_generated_content: true,
  status: 'draft',
})

describe('LogSessionForm — default (real) path', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockGetSessions.mockResolvedValue([])
  })

  it('registers via the real client, persists the draft, and navigates to the default review href', async () => {
    const user = userEvent.setup()
    mockRegisterSession.mockResolvedValue(RESPONSE)
    renderForm()

    await user.type(
      screen.getByLabelText(/what happened/i),
      'The party reached the keep.'
    )
    await user.click(
      screen.getByRole('button', { name: /save session & review memories/i })
    )

    await waitFor(() => {
      expect(mockRegisterSession).toHaveBeenCalledWith(
        'camp-1',
        expect.objectContaining({ summary: 'The party reached the keep.' })
      )
    })
    expect(mockWriteMemoryReviewDraft).toHaveBeenCalledWith(
      expect.objectContaining({
        campaign_id: 'camp-1',
        session_id: 'session-1',
      })
    )
    expect(mockPush).toHaveBeenCalledWith(
      '/campaigns/camp-1/memory/review?session=session-1'
    )
  })
})

describe('LogSessionForm — injected adapter props', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockGetSessions.mockResolvedValue([])
  })

  it('uses registerSessionFn/navigate/persistDraft/reviewHref instead of the real client', async () => {
    const user = userEvent.setup()
    const registerSessionFn = vi.fn().mockResolvedValue(RESPONSE)
    const navigate = vi.fn()
    const reviewHref = vi.fn().mockReturnValue('/demo/memory')

    renderForm({
      registerSessionFn,
      navigate,
      persistDraft: false,
      reviewHref,
    })

    await user.type(
      screen.getByLabelText(/what happened/i),
      'The party reached the keep.'
    )
    await user.click(
      screen.getByRole('button', { name: /save session & review memories/i })
    )

    await waitFor(() => {
      expect(registerSessionFn).toHaveBeenCalledWith(
        'camp-1',
        expect.objectContaining({ summary: 'The party reached the keep.' })
      )
    })
    expect(mockRegisterSession).not.toHaveBeenCalled()
    expect(mockWriteMemoryReviewDraft).not.toHaveBeenCalled()
    expect(reviewHref).toHaveBeenCalledWith({
      campaignId: 'camp-1',
      sessionId: 'session-1',
    })
    expect(navigate).toHaveBeenCalledWith('/demo/memory')
    expect(mockPush).not.toHaveBeenCalled()
  })
})

describe('LogSessionForm — open generated draft', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockCompleteSession.mockResolvedValue(RESPONSE)
    mockRegisterSession.mockResolvedValue(RESPONSE)
  })

  /** Fill the required summary and submit the form. */
  async function submit(user: ReturnType<typeof userEvent.setup>) {
    await user.type(
      screen.getByLabelText(/what happened/i),
      'The party reached the keep.'
    )
    await user.click(
      screen.getByRole('button', { name: /save session & review memories/i })
    )
  }

  it('registers a new session when the campaign has no open draft', async () => {
    const user = userEvent.setup()
    mockGetSessions.mockResolvedValue([session()])
    renderForm()

    await submit(user)

    await waitFor(() => expect(mockRegisterSession).toHaveBeenCalled())
    expect(mockCompleteSession).not.toHaveBeenCalled()
    expect(
      screen.queryByRole('button', { name: /register as a new session/i })
    ).not.toBeInTheDocument()
  })

  it('completes the open draft by default, naming the session it will complete', async () => {
    const user = userEvent.setup()
    mockGetSessions.mockResolvedValue([session(), OPEN_DRAFT])
    renderForm()

    expect(await screen.findByText(/Session 3/)).toBeInTheDocument()
    await submit(user)

    await waitFor(() => {
      expect(mockCompleteSession).toHaveBeenCalledWith(
        'draft-3',
        expect.objectContaining({ summary: 'The party reached the keep.' })
      )
    })
    expect(mockRegisterSession).not.toHaveBeenCalled()
    expect(mockWriteMemoryReviewDraft).toHaveBeenCalledWith(
      expect.objectContaining({
        campaign_id: 'camp-1',
        session_id: 'session-1',
      })
    )
    expect(mockPush).toHaveBeenCalledWith(
      '/campaigns/camp-1/memory/review?session=session-1'
    )
  })

  it('registers a new session when the DM opts out of the draft', async () => {
    const user = userEvent.setup()
    mockGetSessions.mockResolvedValue([OPEN_DRAFT])
    renderForm()

    await user.click(
      await screen.findByRole('button', {
        name: /register as a new session/i,
      })
    )
    await submit(user)

    await waitFor(() => {
      expect(mockRegisterSession).toHaveBeenCalledWith(
        'camp-1',
        expect.objectContaining({ summary: 'The party reached the keep.' })
      )
    })
    expect(mockCompleteSession).not.toHaveBeenCalled()
  })

  it('lets the DM switch back to completing the draft', async () => {
    const user = userEvent.setup()
    mockGetSessions.mockResolvedValue([OPEN_DRAFT])
    renderForm()

    await user.click(
      await screen.findByRole('button', { name: /register as a new session/i })
    )
    await user.click(
      await screen.findByRole('button', { name: /complete session 3/i })
    )
    await submit(user)

    await waitFor(() => expect(mockCompleteSession).toHaveBeenCalled())
    expect(mockRegisterSession).not.toHaveBeenCalled()
  })

  it('ignores sessions that already have consequences or no generated content', async () => {
    const user = userEvent.setup()
    mockGetSessions.mockResolvedValue([
      // Generated, but the outcome is already recorded — not an open draft.
      session({
        id: 'done-1',
        session_number: 1,
        consequences: 'Recorded.',
        has_generated_content: true,
      }),
      // Never generated — an ad-hoc logged session, not a draft.
      session({
        id: 'adhoc-2',
        session_number: 2,
        consequences: null,
        has_generated_content: false,
      }),
    ])
    renderForm()

    await submit(user)

    await waitFor(() => expect(mockRegisterSession).toHaveBeenCalled())
    expect(mockCompleteSession).not.toHaveBeenCalled()
  })

  it('does not offer a summary-only completed generated session as an open draft', async () => {
    const user = userEvent.setup()
    mockGetSessions.mockResolvedValue([
      session({
        id: 'completed-generated',
        session_number: 8,
        summary: 'The party resolved the raid.',
        consequences: null,
        has_generated_content: true,
        status: 'registered',
      }),
    ])
    renderForm()

    await submit(user)

    await waitFor(() => expect(mockRegisterSession).toHaveBeenCalled())
    expect(mockCompleteSession).not.toHaveBeenCalled()
    expect(screen.queryByText(/Session 8/)).not.toBeInTheDocument()
  })

  it('targets the highest-numbered open draft when several exist', async () => {
    const user = userEvent.setup()
    mockGetSessions.mockResolvedValue([
      OPEN_DRAFT,
      session({
        id: 'draft-5',
        session_number: 5,
        consequences: null,
        has_generated_content: true,
        status: 'draft',
      }),
    ])
    renderForm()

    expect(await screen.findByText(/Session 5/)).toBeInTheDocument()
    await submit(user)

    await waitFor(() => {
      expect(mockCompleteSession).toHaveBeenCalledWith(
        'draft-5',
        expect.anything()
      )
    })
  })

  it('degrades to the plain register form when the sessions fetch fails', async () => {
    const user = userEvent.setup()
    mockGetSessions.mockRejectedValue(new Error('network down'))
    renderForm()

    await submit(user)

    await waitFor(() => {
      expect(mockRegisterSession).toHaveBeenCalledWith(
        'camp-1',
        expect.objectContaining({ summary: 'The party reached the keep.' })
      )
    })
    expect(mockCompleteSession).not.toHaveBeenCalled()
    expect(mockPush).toHaveBeenCalledWith(
      '/campaigns/camp-1/memory/review?session=session-1'
    )
  })
})

describe('LogSessionForm — injected draft seam (demo)', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('uses getSessionsFn/completeSessionFn instead of the real client', async () => {
    const user = userEvent.setup()
    const getSessionsFn = vi.fn().mockResolvedValue([OPEN_DRAFT])
    const completeSessionFn = vi.fn().mockResolvedValue(RESPONSE)
    const navigate = vi.fn()

    renderForm({
      getSessionsFn,
      completeSessionFn,
      navigate,
      persistDraft: false,
    })

    expect(await screen.findByText(/Session 3/)).toBeInTheDocument()
    await user.type(
      screen.getByLabelText(/what happened/i),
      'The party reached the keep.'
    )
    await user.click(
      screen.getByRole('button', { name: /save session & review memories/i })
    )

    await waitFor(() => {
      expect(completeSessionFn).toHaveBeenCalledWith(
        'draft-3',
        expect.objectContaining({ summary: 'The party reached the keep.' })
      )
    })
    expect(mockGetSessions).not.toHaveBeenCalled()
    expect(mockCompleteSession).not.toHaveBeenCalled()
    expect(mockRegisterSession).not.toHaveBeenCalled()
  })
})

describe('LogSessionForm — navigation takeover', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('keeps the loading takeover on screen after the mutation resolves', async () => {
    const user = userEvent.setup()
    const registerSessionFn = vi.fn().mockResolvedValue(RESPONSE)
    const navigate = vi.fn()

    renderForm({ registerSessionFn, navigate, persistDraft: false })
    await user.type(
      screen.getByLabelText(/what happened/i),
      'The party reached the keep.'
    )
    await user.click(
      screen.getByRole('button', { name: /save session & review memories/i })
    )

    await waitFor(() => {
      expect(navigate).toHaveBeenCalled()
    })

    // `navigate` only asks for the route swap; the new frame paints later. The
    // form must never flash back in that gap.
    expect(screen.getByText(/chronicling the session/i)).toBeInTheDocument()
    expect(
      screen.queryByRole('button', { name: /save session & review memories/i })
    ).not.toBeInTheDocument()
    expect(screen.queryByLabelText(/what happened/i)).not.toBeInTheDocument()
  })

  it('restores the form when the register fails so the DM can retry', async () => {
    const user = userEvent.setup()
    const registerSessionFn = vi.fn().mockRejectedValue(new Error('network'))
    const navigate = vi.fn()

    renderForm({ registerSessionFn, navigate, persistDraft: false })

    await user.type(
      screen.getByLabelText(/what happened/i),
      'The party reached the keep.'
    )
    await user.click(
      screen.getByRole('button', { name: /save session & review memories/i })
    )

    expect(await screen.findByRole('alert')).toBeInTheDocument()
    expect(
      screen.getByRole('button', { name: /save session & review memories/i })
    ).toBeEnabled()
    expect(navigate).not.toHaveBeenCalled()
  })
})
